# Generated by Django 4.1.7 on 2023-03-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fnames', models.CharField(max_length=30)),
                ('snames', models.CharField(max_length=30)),
                ('classes', models.IntegerField()),
                ('divi', models.CharField(max_length=2)),
            ],
        ),
    ]
